spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: consumer-group-1
      enable-auto-commit: 'false'
      auto-offset-reset: earliest
      bootstrap-servers: 20.63.137.226:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.finmamba
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    bootstrap-servers: 20.63.137.226:9092
    listener:
      poll-timeout: 10000
  datasource:
    username: postgres
    url: jdbc:postgresql://kanjipgdb.postgres.database.azure.com/postgres?sslmode=require 
    password: MErcUry@012
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
        enable_lazy_load_no_trans: 'true'
    hibernate:
      ddl-auto: none
  cache:
    type: redis
  redis:
    host: 20.63.137.226
    port: '6379'
who:
  am:
    i: tester
springdoc:
  api-docs:
    path: /api-docs
  use-fqn: 'true'  

redis:
  hostname: 20.63.137.226
  port: '6379'

